//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duygulu
{
    using System;
    using System.Collections.Generic;
    
    public partial class appuser
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Mail { get; set; }
        public sbyte Authorize { get; set; }
        public Nullable<int> Positiv { get; set; }
        public Nullable<int> Negativ { get; set; }
        public short Stemming1 { get; set; }
        public bool Preprocessing { get; set; }
        public bool StopWord { get; set; }
        public short Stemming2 { get; set; }
        public bool Spelling { get; set; }
        public Nullable<int> Similarity { get; set; }
    }
}
