//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duygulu
{
    using System;
    using System.Collections.Generic;
    
    public partial class searchtable
    {
        public long SearchId { get; set; }
        public Nullable<System.DateTime> SearchDate { get; set; }
        public string SearchText { get; set; }
        public decimal UserId { get; set; }
        public sbyte Authorize { get; set; }
        public Nullable<int> Positiv { get; set; }
        public Nullable<int> Negativ { get; set; }
    }
}
