//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duygulu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tweettable
    {
        public string TweetID { get; set; }
        public Nullable<long> SearchId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string GeoCode { get; set; }
        public string Text { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public Nullable<bool> IsReweet { get; set; }
        public Nullable<decimal> ReTweetCount { get; set; }
        public string HasPhoto { get; set; }
        public Nullable<decimal> FavLike { get; set; }
        public string Text2 { get; set; }
    }
}
