//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duygulu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class twitterdbEntities1 : DbContext
    {
        public twitterdbEntities1()
            : base("name=twitterdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<appuser> appuser { get; set; }
        public DbSet<searchtable> searchtable { get; set; }
        public DbSet<tweettable> tweettable { get; set; }
        public DbSet<usertable> usertable { get; set; }
    }
}
