//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duygulu
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertable
    {
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public string UserScreenName { get; set; }
        public string USerProfileText { get; set; }
        public Nullable<decimal> UserFollowerCount { get; set; }
        public Nullable<decimal> UserFollowingCount { get; set; }
    }
}
